apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: inference-prod
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/adrien-legros/sentiment-analysis.git